### ISSUE TITLE
BUG-000082862  Water Utility Mobile Map Application (10.2) installation executable will not install on 32-bit Windows, throwing an error that file is not compatible with the version of Windows.

Yet if you run the installation file and extract it on a 64-bit Windows and move the extracted folder to a 32-bit windows, the application executable will run.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/water-utility-mobile-map#3]
<div><div>
<span><b>Salesforce ID:</b> BUG-000082862</span><br/>
<span><b>Salesforce Submitter:</b> Brian Watson</span><br/>
<span><b>Salesforce Submit Date:</b> 10/29/2014 6:33 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> Run the installation on 64-bit Windows and copy the installed folder to 32-bit Windows</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> install was built with 64 bit version of IExpress.  Next release we will build with 32 bit to support 32 and 64 os's</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
Triaged
