### ISSUE TITLE
BUG-000083681  Using the Identify tool to select a layer in the Windows Mobile Water Utility Map causes the application to crash.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/water-utility-mobile-map#5]
<div><div>
<span><b>Salesforce ID:</b> BUG-000083681</span><br/>
<span><b>Salesforce Submitter:</b> Matt Monson</span><br/>
<span><b>Salesforce Submit Date:</b> 12/01/2014 1:44 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Crash</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Salesforce Attachments:</b> 11-21-2014 1-22-02 PM.mp4, Customer_Mobile.zip, MobileMapUtilityFolder.zip</span><br/>
<span><b>Salesforce Attachments Location:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000083681</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000083681</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> Windows 7</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> From the stack trace, the issue is probably in the core sdk.  Work around has been implemented to not cause the issue.  Code fix will be delivered with the 10.3 release of the app.</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
Triaged
