### ISSUE TITLE
ENH-000084221  Enhance 'Leak Survey Compliance Dashboard' to display additional useful leak information.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/water-utility-mobile-map#7]
<div><div>
<span><b>Salesforce ID:</b> ENH-000084221</span><br/>
<span><b>Salesforce Submitter:</b> Thomas Noble</span><br/>
<span><b>Salesforce Submit Date:</b> 12/23/2014 12:37 PM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> User does not think the out-of-box widgets are sufficient for complete monitoring of their pipe network.</span><br/>
<span><b>Product:</b> ArcGIS for Utilities and Telecom</span><br/>
<span><b>Functional Category:</b> ArcGIS for Utilities and Telecom</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Enhancement logged</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
closing, logged in wrong repo

**Comment by LindsayThomas** [comment]
TRIAGED
